requestTypes design doc
kyverno/KDP pull request #11
Opened 2022-04-07 18:35 UTC by Prateeknandle

Signed-off-by: Prateeknandle <prateeknandle@gmail.com>

2022-04-11 15:42 UTC, realshuting requested changes
@Prateeknandle - I left a couple of comments below. It seems that there's some misunderstanding about this feature. 

I would suggest reading through this [doc](https://kyverno.io/docs/writing-policies/variables/#pre-defined-variables) to understand how built-in variables work currently, and re-visit this design.

2022-04-11 15:42 UTC, realshuting commented on proposals/add_requestTypes_to_match_&_exclude.md
> +Until now we use request.operation under condition.key, to filter a request, now we'll use a tag requestTypes in match or exclude blocks to match specific requests comming from admission review reque
Typo: "coming"

2022-04-11 15:42 UTC, realshuting commented on proposals/add_requestTypes_to_match_&_exclude.md
> +            value: DELETE
The feature is to add request operations as built-in variables, this validate policy defines nothing else but to reject DELETE requests. Please update this example to reflect some other use case.

2022-04-11 15:42 UTC, realshuting commented on proposals/add_requestTypes_to_match_&_exclude.md
> +When a pod with label `app.kubernetes.io/name: "?*"` is requested to be deleted, the request will match with the requestTypes, but the validate.deny condition will block the delete operation.
Where do we match this label in the above policy?

2022-04-11 15:42 UTC, realshuting commented on proposals/add_requestTypes_to_match_&_exclude.md
> +            value: DELETE
Why do we need this condition?

2022-04-29 15:37 UTC, Prateeknandle commented
> I would suggest reading through this [doc](https://kyverno.io/docs/writing-policies/variables/#pre-defined-variables) to understand how built-in variables work currently, and re-visit this design.

@realshuting we don't need to assign the value to `request.operation` as shown in [here](https://kyverno.io/docs/writing-policies/variables/#pre-defined-variables), for different variables, because kubernetes-api will assign request-type, value to the variable `request.operation`.
So basically we need to access the `request.operation` and then use it's value to match with the new tag `requestTypes`.
Is this correct?

2022-05-03 09:37 UTC, Prateeknandle commented
Need to close this pr, actually I pushed it from main branch, reopening new pr. 
Sorry for the inconvenience

2022-05-03 09:37 UTC, closed without merging