doc(KDP): add policy status KDP
kyverno/KDP pull request #64
Opened 2024-12-10 15:24 UTC by KhaledEmaraDev

2025-01-17 16:56 UTC, JimBugwadia requested changes

2025-01-17 16:56 UTC, JimBugwadia commented on proposals/policy_status.md
> +- `CachePresence`: Indicates whether the policy has been successfully loaded into Kyverno's internal cache.
```suggestion
- `PolicyCached`: Indicates whether the policy has been successfully loaded into Kyverno's internal cache.
```

2025-01-17 16:56 UTC, JimBugwadia commented on proposals/policy_status.md
> +- `RBACPermissions`: Indicates whether Kyverno has the necessary RBAC permissions to enforce the policy.
```suggestion
- `RBACPermissionsGranted`: Indicates whether Kyverno has the necessary RBAC permissions to enforce the policy.
```

2025-01-17 16:56 UTC, JimBugwadia commented on proposals/policy_status.md
> +Each condition will have a status of `True` or `False`. If a condition's type is `NotReady` and the status is `False`, the policy will fail to apply unless explicitly configured otherwise through `va
> If a condition's type is `NotReady` and

What is this referring to....is there a `type`?

2025-01-17 16:56 UTC, JimBugwadia commented on proposals/policy_status.md
> +[proposal]: #proposal
I recommend we keep the `status` field with values `Ready` and `NotReady` as a summary state. We can set `status: Ready` when all conditions pass.

2025-01-20 09:29 UTC, KhaledEmaraDev commented on proposals/policy_status.md
> +[proposal]: #proposal
So, first I think it's deprecated. I will try to get a reference to this. Second, for future proofing I was thinking that different components might interpret conditions differently. So for instance, the background controller might not care about a policy being configured in the webhook or not. Ready here should be false for Admission but true for Background.

I think it's better if we leave each component to interpret the readiness on its own. But, I'm also fine with this.

2025-01-20 09:30 UTC, KhaledEmaraDev commented on proposals/policy_status.md
> +Each condition will have a status of `True` or `False`. If a condition's type is `NotReady` and the status is `False`, the policy will fail to apply unless explicitly configured otherwise through `va
Good catch. This is a typo. The types are what we defined above.

2025-05-14 08:51 UTC, closed without merging